FROM tomcat:8.0-alpine

LABEL maintainer="patilbhagyashri598@gmail.com"

RUN apk --update add openjdk8-jre

COPY docker-hello-world-example.jar app.jar

ADD sample.war /usr/local/tomcat/webapps/

EXPOSE 8080

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar"]
